### ISSUE TITLE
Add "Compile to Schematic"

### ISSUE THREAD

**Issue by BrainStone** [Adrodoc55/MPL#21]
It would be nice to add a feature to compile the command blocks to a schematic file so you can import the structures with something like worldedit

**Comment by Adrodoc55** [comment]
I wasn't able to find a working java library that'd allow me to generate a schematic file. As a workaround there is the option to compile to a python file that can be imported as a filter via mcedit.

**Comment by Adrodoc55** [comment]
If you know of a java library that can create schematik files please let me know!

**Comment by Adrodoc55** [comment]
After a lot of searching and trying I actually got a library to work :D

**Comment by Adrodoc55** [comment]
@BrainStone Do you want me to build a new release for this feature, or do you not need it currently?

**Comment by BrainStone** [comment]
Thank you!
If you wouldn't mind a new release would be lovely!

**Comment by Adrodoc55** [comment]
@BrainStone I'll draft a new release, when I come home (~22:00 CET).
Have you already been using MPL? If so I'd love to hear your opinion on it!

**Comment by Adrodoc55** [comment]
@BrainStone New release is out: https://github.com/Adrodoc55/MPL/releases/tag/v0.9

**Comment by BrainStone** [comment]
@Adrodoc55 Thank you!
Yes I have been using it. Just not yet for something big. I think it is very good!
I also have a few more suggestions. Should I post them here as a new issue or in some other way.

**Comment by Adrodoc55** [comment]
@BrainStone It would be best to post each suggestion as a separate issue. That way it is easier to decide which ones will be implemented and I can close finished ones.
