### ISSUE TITLE
Add compile time functions and loops

### ISSUE THREAD

**Issue by BrainStone** [Adrodoc55/MPL#25]
It would be wonderful to have a feature that allows functions to be compiled during runtime.

Example:

```
function hello (
  /say Hello!
  /say How are you?
)

process main (
  hello
  /tp @a ~ ~10 ~
  hello
)
```

This should generate the following code before it gets compiled into command blocks

```
process main (
  /say Hello!
  /say How are you?
  /tp @a ~ ~10 ~
  /say Hello!
  /say How are you?
)
```

Also having the possibility to add parameters would be amazing!
Suggested syntax

```
function tp_player($x, $y, $z) (
  /tp @p $x, $y, $z
)

process main (
  tp_player(1, 2, ~10)
)
```

Generates:

```
process main (
  /tp @p 1 2 ~10
)
```

Also for loops during compile time:

```
process main (
  for $x from -10 to 10 step 5: (
    /tp @p $x 2 ~10
  )
)
```

```
process main (
  /tp @p -10 2 ~10
  /tp @p -5 2 ~10
  /tp @p 0 2 ~10
  /tp @p 5 2 ~10
  /tp @p 10 2 ~10
)
```

**Comment by Adrodoc55** [comment]
This issue has been split into #34 and #43, because it requests two seperate features. Any further development will be based on those issues.
