### ISSUE TITLE
Process modifer

### ISSUE THREAD

**Issue by Adrodoc55** [Adrodoc55/MPL#34]
`remote`: process must always be called remotely and can't be inlined.
`global`/`runtime`/`public`: process will be inlined, but will also be available at runtime. Warning: waiting for or intercepting this process will only work when called remotely by a different project.
`inline`/`compiletime`/`private`: process will not be available at runtime and can't be intercepted or waited for. This enables `string` parameters. This should be the default.

**Comment by Adrodoc55** [comment]
If the keyword `clickabe` from #23 is added it will only work with processes that are available at runtime.

**Comment by BrainStone** [comment]
I would choose the keywords ``remote``, ``global`` and ``inline``.
I also agree that ``inline`` should be a implicit keyword

**Comment by Adrodoc55** [comment]
I suspect that the second type will not be used very often and the second type is basically a mix of the other two. I don't really like the keyword `global`, because it does not really describe it's meaning accurate ly. Maybe it would make sence to use both of the other keywords to mark a type 2 process: `inline remote process myProcess`.
Something to keep in mind is that the keyword `compiletime` might be required for #25 and could the be reused here.

**Comment by Adrodoc55** [comment]
Starting, stopping, intercepting or waiting for an inline process should result in a compiler error.

**Comment by Adrodoc55** [comment]
`global`/`runtime`/`normal` processes were not added. They might possibly be added in the future.
